version: '2'
services:
  web:
      build: .
      command: yarn start
      volumes:
          - ./db.sql:/var/www/nasa/db.sql
      env_file:
        - ./.env
      ports:
          - "4000:4000"
      restart: on-failure

